### ISSUE TITLE
Cart Page

### ISSUE THREAD

**Issue by katyjmt** [ecommerce-fashion-designer/fashion-designer#2]
- [ ] List products that have 'InCart' as true in db (filter by user id) - display product name, image, price in list
- [ ] Sum total of product prices
- [ ] Checkout button

![Image](https://github.com/ecommerce-fashion-designer/fashion-designer/assets/43462706/33445933-0e59-4088-90e9-a82f6ec9eb58)

**Comment by katyjmt** [comment]
- [ ] List products that have 'InCart' as true in db (filter by user id) - display product name, image, price in list
- [ ] Sum total of product prices
- [ ] Checkout button

**Comment by higgdan** [comment]
Cart page utilises helpers and some frontend JS to calculate the quantity multiplier and subtotal.
Layout done entirely with bootstrap within the view pages.
